import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GiClockwork} from 'react-icons/gi'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <GiClockwork size={100} color='#05a081'></GiClockwork>
        <h1 style={{color:'#05a081', fontWeight:'bold', fontSize:40}}>
          TAGUA WEBPAGE IN PROGRES ...
        </h1>
      </main>
    </div>
  )
}
